### ISSUE TITLE
Subtype C

### ISSUE THREAD

**Issue by roryk** [kantorlab/hivmmer#3]
Hey everyone,

How hard would it be to implement support for subtype C? I'm happy to do this if you could all point me at what would have to happen to add support. I looked through the code and it looks like it would be pretty straightforward, but was wondering what you think.

**Comment by mhowison** [comment]
Hi @roryk, would you need to use different indexing than HXB2? If so, you would need to modify the hard-coded sequence ID in `hivmmer-trim-reference` to reflect your indexing sequence.

If not, then you should be able to use the pipeline as-is. You could use the default reference pHMM which includes all HIV-1 Group M sequences from the Los Alamos database. Or if you prefer to use a more C-specific set of sequences, you could build your own pHMM reference using the instructions under [Preparing a pHMM reference](https://github.com/kantorlab/hivmmer#preparing-a-phmm-reference) in the README.

Hope that helps!

**Comment by roryk** [comment]
Awesome, thanks so much for answering. Sounds good, I'll swap the ID since we are going to be using subtype C. In the publication you mentioned that you had only tested it on the pol region, have you done any work on the env region since then? If so, do you have any tips?

**Comment by mhowison** [comment]
Hi @roryk, I wanted to let you know that version 0.2.0 of hivmmer will include support for the whole HIV genome, including the env region. Stay tuned!

**Comment by mhowison** [comment]
Hi @roryk, FYI we have released hivmmer version 0.2.0 which provides built-in support for whole HIV genome alignment.
