### ISSUE TITLE
What should I be using as a reference?

### ISSUE THREAD

**Issue by drescs** [kantorlab/hivmmer#4]
I'm having trouble getting the reference to work--can you help me figure out how to specify one of the pre-built alignments? 

Thank you!

**Comment by drescs** [comment]
For example, I am getting this error when trying to build my own reference:
 "File "/app/easybuild/software/hivmmer/0.1.2-foss-2016b-Python-3.6.6/bin/hivmmer-trim-reference", line 16, in <module>
    coords = [i for i, nt in enumerate(hxb2.seq) if nt != '-']
NameError: name 'hxb2' is not defined"

There is definitely a correctly named HXB2 sequences in my fasta file--if you can help me figure out how to fix this I would really appreciate this.

**Comment by mhowison** [comment]
Hi @drescs, is your HXB2 sequence in your FASTA reference named "B.FR.83.HXB2_LAI_IIIB_BRU.K03455"? This is the name that the `hivmmer-trim-reference` script looks for, since it is the name for HXB2 in the LANL alignments we used for our references. At some point, I could add an option to the script to use a different name, but the fastest way to use the current version of hivmmer would be to rename your HXB2 sequence using that name.

**Comment by drescs** [comment]
Ours seems to be named ">Ref.B.FR.83.HXB2_LAI_IIIB_BRU.K03455" so I'll try removing "Ref." to see if that fixes the issue. Thank you. Additionally, I was able to get the pol segment to work with your pre-made reference. I'm hoping to find minority variants and their frequencies. Am I right that I should be using the [mysample].hmmsearch2.aavf file to find this information?

Can I also ask--we have sequenced amplicons that span ~ 1/2 of pol. Should I be trimming the reference to match our amplicon, or will that sort of "come out in the wash" because coverage should be quite low outside those regions?

And lastly--in the aavf file, where we have "position"--is this relative to HXB2, or to the start of the sample specific consensus? Or to the gene? As it starts with position 1, I imagine it is to either the sample specific consensus or the HXB2 gene?

Thank you!

Sara

**Comment by mhowison** [comment]
Hi Sara, version 0.2.0 of hivmmer will include prepackaged profile Hidden Markov Models for the entire HIV genome. This should make it much easier for you to work with regions outside of pol! And you won't need to use the hivmmer-trim-reference script to create your own pHMM. Stay tuned!

**Comment by mhowison** [comment]
Hi @drescs, FYI we have released hivmmer version 0.2.0 which provides built-in support for whole HIV genome alignment with prepackaged references from LANL.

**Comment by nadine-zakkak** [comment]
Hello
I am also trying to run hivmmer, but I am having troubles with the reference! I only care about the pol gene. I tried building my own pHMM using hmmbuild but apparently there is a problem in my file although I downloaded it from the Los Alamos database. 
I found the prepackaged hmm indexed files, but how do I use them as my reference?
Could you please help me to figure this out?
Thank you.
