### ISSUE TITLE
support for Gag?

### ISSUE THREAD

**Issue by drescs** [kantorlab/hivmmer#5]
I noticed that there is no option to specify "gag" as the region. I made my own reference (thanks for the help with that) for gag but seems a region must be specified from pol, int, or env. It looks like maybe this is only used for noting what gene a codon is in--if that is the case, can I just use int as the region, or is there more going on here? Or can I change the code to add "gag" as an option for the reference?

Thank you!
Sara

**Comment by mhowison** [comment]
Hi Sara, sorry for the delay in responding to you on this, but I wanted to let you know that support for gag (and in fact the whole HIV genome) is planned for version 0.2.0 of hivmmer. I will send you an update when that version is released.

**Comment by drescs** [comment]
Thank you Mark. I actually was able to get a fairly good workaround by
creating my own gag reference but setting the fragment to "int." In fact
for my application I am setting the fragment to int for my pol sequences as
well, so that I get all AA positions in the variants file, rather than just
those relevant to drug resistance. It seems to be working well!
